name: Daily Job


on:
  pull_request:
    branches: [ main ]  # o 'master' si esa es tu rama principal
  push:
    branches: [ main ]  # o 'master' si esa es tu rama principal

jobs:
  run-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run script
        run: |
          python main.py

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with: 
          commit_message: Update completed
          github_token: ${{ secrets.GITHUB_TOKEN }}

